# Site settings
title: DJ DeFi
description: > # this means to ignore newlines until "baseurl:"
  DJ DeFi west coast Drum and Bass
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://djdefi.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

remote_theme: andrewbanchich/highlights-jekyll-theme

twitter_url: https://twitter.com/djdefi
github_url: https://github.com/djdefi

plugins:
  - jekyll-seo-tag
