# Site settings
title: DJ DeFi
description: > # this means to ignore newlines until "baseurl:"
  DJ DeFi west coast Drum and Bass
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://djdefi.com" # the base hostname & protocol for your site
twitter_username: djdefi

# Build settings
markdown: kramdown

gems:
  - jekyll-seo-tag
